apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: trs.sde.dev
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: sde.dev
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: trs
    # singular name to be used as an alias on the CLI and for display
    singular: tr
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: TaskRun
    listKind: TaskRunList
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - tr
    versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                message:
                  type: string
                count:
                  type: integer
            status:
              type: object
              properties:
                message:
                  type: string
                count:
                  type: integer
  ownerReferences:
    - apiVersion: sde.dev/v1alpha1
      kind: PipelineRun
      name: "{{ .Values.prName }}"
      blockOwnerDeletion: true